
services:
  - type: web
    name: admanager-middleware
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: ADMANAGER_URL
        value: https://proyecto.melabs.tech:8443/RestAPI/SearchUser
      - key: ADMANAGER_TOKEN
        value: d894b0a9-7c9a-4c89-85e6-4cc97fa695ed
      - key: ADMANAGER_DOMAIN
        value: cybersex.com
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: admananger665@gmail.com
      - key: SMTP_PASSWORD
        value: uutlxitfiibebmpg
